/*
MAKE AN ARRAY BASED DRIVE,
IF POSSIBLE, STORE THE X, Y, AND ROTATION_DEGREES INSIDE OF VECTOR3'S IN THE ARRAY,
MAKE A FOR LOOP TO SETUP THE PATH,
MAKE A VARIABLE THAT TRACKS WHICH PATH IS BEING USED
*/

package org.firstinspires.ftc.teamcode.Autonomous;

public class YEPPAuto {
}
